/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio1;

import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estudiante
 */
public class formulario1 extends javax.swing.JFrame {

    /**
     * Creates new form formulario1
     */
    DefaultTableModel modeloTabla;
    Conexion con= new Conexion();
    public formulario1() {
        
        modeloTabla= new DefaultTableModel(null, getColumnas());
        setFilas();
        
        initComponents();
        setLocationRelativeTo(null);
        
        ImageIcon foto = new ImageIcon (getClass().getResource("/imagenes/agregar.png"));
        ImageIcon icono = new ImageIcon(foto.getImage().getScaledInstance(agregar.getWidth(),agregar.getHeight(),Image.SCALE_DEFAULT));
        agregar.setIcon(icono);
        
        ImageIcon foto1 = new ImageIcon (getClass().getResource("/imagenes/modificar.png"));
        ImageIcon icono1 = new ImageIcon(foto1.getImage().getScaledInstance(modificar.getWidth(),modificar.getHeight(),Image.SCALE_DEFAULT));
        modificar.setIcon(icono1);
        
        ImageIcon foto2 = new ImageIcon (getClass().getResource("/imagenes/eliminar.png"));
        ImageIcon icono2 = new ImageIcon(foto2.getImage().getScaledInstance(eliminar.getWidth(),eliminar.getHeight(),Image.SCALE_DEFAULT));
        eliminar.setIcon(icono2);
        
        ImageIcon foto3 = new ImageIcon (getClass().getResource("/imagenes/guardar.png"));
        ImageIcon icono3 = new ImageIcon(foto3.getImage().getScaledInstance(buscar.getWidth(),buscar.getHeight(),Image.SCALE_DEFAULT));
        buscar.setIcon(icono3);
        
        ImageIcon foto4 = new ImageIcon (getClass().getResource("/imagenes/actualizar.png"));
        ImageIcon icono4 = new ImageIcon(foto4.getImage().getScaledInstance(actualizar.getWidth(),actualizar.getHeight(),Image.SCALE_DEFAULT));
        actualizar.setIcon(icono4);
        
    }
    private String[] getColumnas(){
        String columnas[] = new String[]{"CODIGO","NOMBRE","AÑO","COSTO","FECHA REGISTRO"};
        return columnas;
    }
    private void setFilas(){
        try{
            String consulta = "SELECT codigo_proyecto, nombre_proyecto, anio_creacion, costo, fecha_creacion FROM proyectos";
            
                PreparedStatement us = con.conectar().prepareStatement(consulta);
                ResultSet resultado = us.executeQuery();
                
                Object datos[]= new Object[5];
                
                while(resultado.next()){
                    for (int i = 0; i <datos.length; i++) {
                        datos[i]= resultado.getObject(i+1);
                    }
                    modeloTabla.addRow(datos);
                }
        }
        catch(Exception e){
            
                
            }
            
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        costo = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        buscar = new javax.swing.JLabel();
        agregar = new javax.swing.JLabel();
        modificar = new javax.swing.JLabel();
        eliminar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        actualizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Proyectos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 166, 170));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(34, 166, 170));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel2.setText("Fecha Registro:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, 30));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel3.setText("Codigo:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel5.setText("Año:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel6.setText("Costo ($):");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 30));
        jPanel3.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 150, 30));
        jPanel3.add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 100, 30));
        jPanel3.add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, 30));
        jPanel3.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 100, 30));
        jPanel3.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 30));

        buscar.setText("Button1");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        jPanel3.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 50, 50));

        agregar.setText("Button1");
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        jPanel3.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 50, 50));

        modificar.setText("Button1");
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        jPanel3.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 50, 50));

        eliminar.setText("Button1");
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });
        jPanel3.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 50, 50));

        jTable2.setBackground(new java.awt.Color(204, 255, 255));
        jTable2.setModel(modeloTabla );
        jTable2.setGridColor(new java.awt.Color(102, 102, 102));
        jTable2.setSelectionForeground(new java.awt.Color(13, 51, 62));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 530, 190));

        jButton1.setText("Limpiar Campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 130, 50));

        actualizar.setText("Button1");
        actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarMouseClicked(evt);
            }
        });
        jPanel3.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 50, 50));

        jTabbedPane1.addTab("Proyectos", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 670, 396));

        jPanel2.setBackground(new java.awt.Color(13, 51, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(182, 189, 11));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(182, 189, 11));
        jLabel1.setText("Gestion de Proyectos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        // TODO add your handling code here:
        MtoProyectos objeto = new MtoProyectos();
        objeto.setCodigo(Integer.parseInt(codigo.getText()));
        objeto.setNombre(nombre.getText());
        objeto.setAnio(año.getText());
        objeto.setCosto(Double.parseDouble(costo.getText()));
        objeto.setFecha(fecha.getText());
        
        if (objeto.guardarProyecto()) {
            JOptionPane.showMessageDialog(this, "Datos Guardados");
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }  
        int filas=modeloTabla.getRowCount();
                for (int i = 0; filas>i; i++) {
                    modeloTabla.removeRow(0);
                }
                    setFilas();
    }//GEN-LAST:event_agregarMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        // TODO add your handling code here:
        MtoProyectos objeto = new MtoProyectos();
        objeto.setCodigo(Integer.parseInt(codigo.getText()));
        objeto.setNombre(nombre.getText());
        objeto.setAnio(año.getText());
        objeto.setCosto(Double.parseDouble(costo.getText()));
        objeto.setFecha(fecha.getText());
        
        if (objeto.modificarProyecto()) {
            JOptionPane.showMessageDialog(this, "Datos Modificados");
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        } 
        int filas=modeloTabla.getRowCount();
        for (int i = 0; filas>i; i++) {
            modeloTabla.removeRow(0);
        }
            setFilas();
    }//GEN-LAST:event_modificarMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        // TODO add your handling code here:
        MtoProyectos objeto = new MtoProyectos();
        objeto.setCodigo(Integer.valueOf(codigo.getText()));
        int eliminar= JOptionPane.showConfirmDialog(this, "¿Estas seguro de eliminar este proyecto", "Atencion", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (eliminar==0) {
           if (objeto.eliminarProyecto()) {
            JOptionPane.showMessageDialog(this, "Datos Eliminados");
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }  
        }
        int filas=modeloTabla.getRowCount();
        for (int i = 0; filas>i; i++) {
            modeloTabla.removeRow(0);
        }
            setFilas();
    }//GEN-LAST:event_eliminarMouseClicked

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        // TODO add your handling code here:
        MtoProyectos objeto = new MtoProyectos();
        objeto.setCodigo(Integer.valueOf(codigo.getText()));
        
        if (objeto.consultarProyecto()) {
            nombre.setText(""+objeto.getNombre());
            año.setText(""+objeto.getAnio());
            costo.setText(""+objeto.getCosto());
            fecha.setText(""+objeto.getFecha());
        } else {
            JOptionPane.showMessageDialog(this, "Datos No Encontrados");
        }  
        int filas=modeloTabla.getRowCount();
        for (int i = 0; filas>i; i++) {
            modeloTabla.removeRow(0);
        }
            setFilas();
    }//GEN-LAST:event_buscarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        codigo.setText(null);
        nombre.setText(null);
        año.setText(null);
        costo.setText(null);
        fecha.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMouseClicked
        // TODO add your handling code here:
        int filas=modeloTabla.getRowCount();
        for (int i = 0; filas>i; i++) {
            modeloTabla.removeRow(0);
        }
            setFilas();
        
    }//GEN-LAST:event_actualizarMouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        codigo.setText(String.valueOf(modeloTabla.getValueAt(jTable2.getSelectedRow(),0)));
        nombre.setText(String.valueOf(modeloTabla.getValueAt(jTable2.getSelectedRow(),1)));
        año.setText(String.valueOf(modeloTabla.getValueAt(jTable2.getSelectedRow(),2)));
        costo.setText(String.valueOf(modeloTabla.getValueAt(jTable2.getSelectedRow(),3)));
        fecha.setText(String.valueOf(modeloTabla.getValueAt(jTable2.getSelectedRow(),4)));
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualizar;
    private javax.swing.JLabel agregar;
    private javax.swing.JTextField año;
    private javax.swing.JLabel buscar;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField costo;
    private javax.swing.JLabel eliminar;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel modificar;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
